Universe part
kuruma99/Lean.DataSource.CoinGeckoMarketCap pull request #12
Opened 2022-05-24 13:42 UTC by kuruma99

2022-05-24 14:43 UTC, AlexCatarino requested changes
Thank you, @kuruma99.
The main issue is not adding the coin name. Also, please add sample data, and test the algorithm.

2022-05-24 14:43 UTC, AlexCatarino commented on CoinGeckoMarketCapUniverseSelectionAlgorithm.cs
> +                       select d.Symbol;
We cannot return the Symbol, but a combination of the Base Currency (Coin) and the Quote Currency (e.g. USD) to create a `Symbol`.

2022-05-24 14:43 UTC, AlexCatarino commented on CoinGeckoMarketCapUniverse.cs
> +            return $"{Symbol} - Marketcap : {Marketcap}";
```csharp
return $"{Coin}.{Symbol} - Marketcap : {Marketcap}";
```

2022-05-24 14:43 UTC, AlexCatarino commented on CoinGeckoMarketCapUniverse.cs
> +    {
```csharp
        /// <summary>
        /// Coin name
        /// </summary>
        public string Coin { get; set; }
```

2022-05-24 14:43 UTC, AlexCatarino commented on CoinGeckoMarketCapUniverse.cs
> +        public TimeSpan Period { get; set; } = TimeSpan.FromDays(1);
```csharp
private TimeSpan _period = TimeSpan.FromDays(1);
```

2022-05-27 11:15 UTC, uldrim commented
I have backtested the universe algorithm and the output is correct. Attaching the result of the demo algo along with the raw data retrieved from the CoinGecko API(in the output directory).
The dates used in the demo algo are Feb 14'2022 - Feb 18' 2022
<img width="687" alt="output" src="https://user-images.githubusercontent.com/45782936/170688862-b05676b8-f82d-46e4-a653-50a3ba063f5b.png">
<img width="161" alt="btc_universe" src="https://user-images.githubusercontent.com/45782936/170689301-d008ca3c-be9c-4c24-8220-602913f2a206.png">
<img width="170" alt="eth_universe" src="https://user-images.githubusercontent.com/45782936/170689305-4296630b-8d29-4e5f-bfaf-6f2189e4eae2.png">

2022-05-27 17:36 UTC, uldrim commented
The final output of the demo algorithm.
<img width="659" alt="output2" src="https://user-images.githubusercontent.com/45782936/170762303-50e271a5-f431-41ae-b6bf-44a02c802d9c.png">
The output is consistent with the data files in https://github.com/kuruma99/Lean.DataSource.CoinGeckoMarketCap/tree/master/output/alternative/coingecko/marketcap/universe

2022-05-27 17:50 UTC, merged