data source and processing
kuruma99/Lean.DataSource.CoinGeckoMarketCap pull request #7
Opened 2022-05-10 13:32 UTC by kuruma99

1) Adding all the required files
2) The output of the demo algorithm is matching with the raw data (Attaching screenshots for the same)
3) The data being populated in the output/alternative/coingecko/marketcap directory is matching with the data available on Coingecko website (matched it by creating a GET request to coingecko API at /coins/{id}/history endpoint by specifying the particular dates and matching them)
<img width="148" alt="btc" src="https://user-images.githubusercontent.com/45782936/167640583-3a42ac64-8ae4-4f53-a06a-b8955a47f5b4.png">
<img width="714" alt="log2" src="https://user-images.githubusercontent.com/45782936/167640597-263304e8-2067-4ae5-93b2-0f1964a101d6.png">

2022-05-10 13:56 UTC, kuruma99 commented
I have also added the data files for top 5 coins.
The marketcap for any particular date can be matched using the coingecko api endpoint '/coins/{id}/history'.
For example : 'https://api.coingecko.com/api/v3/coins/bitcoin/history?date=07-10-2013&localization=false'

2022-05-10 14:08 UTC, LouisSzeto approved these changes
Awesome! Just some minor comments.

2022-05-10 14:08 UTC, LouisSzeto commented on CoinGeckoMarketCapAlgorithm.cs
> +            _cryptoSymbol = AddCrypto("BTCUSD").Symbol;
This line seems redundant as it is not used.

2022-05-10 14:08 UTC, LouisSzeto commented on CoinGeckoMarketCapAlgorithm.py
> +        self.crypto_symbol = self.AddEquity("BTCUSD", Resolution.Daily).Symbol
Same comment.

2022-05-10 14:08 UTC, LouisSzeto commented on process.py
> +  print("Total time taken to run in minutes : ", time_taken//60)
Can you fix the nit here? 
Some of them use "Tab", some with "2 spaces" and some with "4 spaces". We should use "4 spaces" for all indents.

For all files: please remove any tab or space for the empty lines with no code.

2022-05-12 14:40 UTC, AlexCatarino requested changes
Thank you for the contribution, @kuruma99.
Louis and I have minor comments mostly on using AddCrypto unnecessarily.

Additionally, I looks that has been a merge issue, please check out
[bnb.csv#L1693:L1700](
https://github.com/kuruma99/Lean.DataSource.CoinGeckoMarketCap/blob/master/output/alternative/coingecko/marketcap/bnb.csv#L1693:L1700)

2022-05-12 14:40 UTC, AlexCatarino commented on listing-about.md
> +self.btcusd = self.AddCrypto("BTCUSD", Resolution.Daily).Symbol
Here we just want to teach how to add data of this dataset, so we don't need to add crypto. This is in line with Louis' comments above.

2022-05-12 14:40 UTC, AlexCatarino commented on listing-about.md
> +btcusd = AddCrypto("BTCUSD", Resolution.Daily).Symbol;
Same as previous.

2022-05-12 14:40 UTC, AlexCatarino commented on listing-about.md
> +- **Data Density**: Dense
`Dense` is reserved for tick resolution data. In this case, the density is "regular".

2022-05-19 17:12 UTC, merged